apiVersion: apps/v1
kind: Deployment
metadata:
  name: academy-stack
  namespace: academy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: academy-web
  template:
    metadata:
      labels:
        app: academy-web
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: shared-files
        emptyDir: {} # Creates a shared storage volume between both containers

      # This copies your Laravel build files into the shared storage volume before starting
      initContainers:
      - name: code-provider
        image: vaibhav6060/academy:latest
        imagePullPolicy: Always
        command: ["cp", "-a", "/var/www/html/.", "/var/www/shared"]
        volumeMounts:
        - name: shared-files
          mountPath: /var/www/shared

      containers:
      # --- Container 1: PHP-FPM (Laravel Application) ---
      - name: laravel
        image: vaibhav6060/academy:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        env:
        - name: DB_HOST
          valueFrom: { secretKeyRef: { name: academy-db-secret, key: DB_HOST } }
        - name: DB_DATABASE
          valueFrom: { secretKeyRef: { name: academy-db-secret, key: DB_DATABASE } }
        - name: DB_USERNAME
          valueFrom: { secretKeyRef: { name: academy-db-secret, key: DB_USERNAME } }
        - name: DB_PASSWORD
          valueFrom: { secretKeyRef: { name: academy-db-secret, key: DB_PASSWORD } }
        volumeMounts:
        - name: shared-files
          mountPath: /var/www/html

      # --- Container 2: Nginx Web Server ---
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        - name: shared-files
          mountPath: /var/www/html
